### ISSUE TITLE
[todo] 1006 todo

### ISSUE THREAD

**Issue by oldiepuppie** [codestates/AnimalChat#40]
### wiki
- [x] wire frame
- [x] db schema
- [x] api document
- [x] Not To Do 리스트 점검

### code states form
- [x] 프로젝트 기획 설문조사
- [x] KPT

### issue card
- [x] 태스크 카드 작성 및 분배
